---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gnlist-pv
  namespace: gn
  labels:
    name: gnlist-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/gnlist

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gnlist-uploads-pv
  namespace: gn
  labels:
    name: gnlist-uploads-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/gnlist-uploads

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gnlist-results-pv
  namespace: gn
  labels:
    name: gnlist-results-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/gnlist-results
