AllCops:
  Exclude:
    - db/**/*
    - bundle_bin/**/*
    - spec/**/*
    - node_modules/**/*
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/DotPosition:
  EnforcedStyle: trailing
Security/YAMLLoad:
  Enabled: false
