apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gnlist-pvc
  namespace: gn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: gnlist-pv


