---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gnlist-pvc
  namespace: gn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: gnlist-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gnlist-results-pvc
  namespace: gn
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: gnlist-results-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gnlist-uploads-pvc
  namespace: gn
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: gnlist-uploads-pv
