apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gnlist-pv-claim
  namespace: gn
  # annotations:
  #   volume.beta.kubernetes.io/storage-class: "fast"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: gnlist-pv


